name: Metrics
on:
  # Atualiza as 00:00 todos os dias
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente na aba Actions
  workflow_dispatch:
  # Roda quando há push na branch main/master
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu token secreto criado no passo 1
          token: ${{ secrets.METRICS_TOKEN }}

          # Opções Gerais
          user: leanoguerreiro
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Plugin: Linguagens (Substitui o top-langs)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: bytes-size, percentage
          
          # Plugin: Isocalendar (Substitui o gráfico de contribuição simples por um 3D)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Plugin: Lines (Mostra linhas de código adicionadas - opcional, mas legal)
          plugin_lines: yes
          
          # Plugin: Habits (Mostra horários que você mais coda)
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
