name: Metrics
on:
  # Atualiza às 00:00 todos os dias
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente
  workflow_dispatch:
  # Roda quando há push na branch main/master
  push: {branches: ["master", "main", "develop", "Develop", "release", "Release"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # --- Configurações Visuais ---
          user: leanoguerreiro
          template: classic
          config_timezone: America/Manaus
          
          base: header, activity, repositories, community
          
          # --- Plugin: Linguagens ---
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          plugin_languages_colors: github
          
          # --- Plugin: Calendário 3D (Destaque) ---
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # --- Plugin: Linhas de Código ---
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, languages, projects

          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 12
